language: python
python:
  - "2.7"
  - "3.3"
  - "pypy"
install:
  - sudo apt-get update && sudo apt-get upgrade -y
  - sudo apt-get install libmagic-dev
  - pip install -r requirements.txt
script:
  - nosetests
